Rails.application.routes.draw do
  resources :friends
  # get 'home/index'

  get 'home/about'

  # this is gotten from 'Home' view and index method within Home controller -- the connection is made as we autogenerated with rails g controller home index
  root 'home#index' #changes index page to our root

  # Defines the root path route ("/")
  # root "articles#index"
end
